import product1 from "./assets/products/Dove/Dress1.png";
import product2 from "./assets/products/Grape.png";

export const PRODUCTS = [
  {
    id: 1,
    productName: "Dress1",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/dove/doveProduct1",
  },
  {
    id: 2,
    productName: "Dress2",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/dove/doveProduct2",
  },
  {
    id: 3,
    productName: "Dress1",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/dove/doveProduct1",
  },
  {
    id: 4,
    productName: "Dress2",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/dove/doveProduct2",
  },
  {
    id: 5,
    productName: "Dress1",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/dove/doveProduct1",
  },
  {
    id: 6,
    productName: "Dress2",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/dove/doveProduct2",
  },
  {
    id: 7,
    productName: "Dress1",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/dove/doveProduct1",
  },
  {
    id: 8,
    productName: "Dress2",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/dove/doveProduct2",
  },
  {
    id: 9,
    productName: "Dress9",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/hummingBird/hummingBirdProduct1",
  },
  {
    id: 10,
    productName: "Dress10",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/hummingBird/hummingBirdProduct2",
  },
  {
    id: 11,
    productName: "Dress11",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/hummingBird/hummingBirdProduct3",
  },
  {
    id: 12,
    productName: "Dress12",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/hummingBird/hummingBirdProduct4",
  },
  {
    id: 13,
    productName: "Dress13",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/hummingBird/hummingBirdProduct5",
  },
  {
    id: 14,
    productName: "Dress14",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/hummingBird/hummingBirdProduct6",
  },
  {
    id: 15,
    productName: "Dress15",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/puffin/puffinProduct1",
  },
  {
    id: 16,
    productName: "Dress16",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/puffin/puffinProduct2",
  },
  {
    id: 17,
    productName: "Dress17",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/puffin/puffinProduct3",
  },
  {
    id: 18,
    productName: "Dress18",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/puffin/puffinProduct4",
  },
  {
    id: 19,
    productName: "Dress19",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/puffin/puffinProduct5",
  },
  {
    id: 20,
    productName: "Dress20",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/puffin/puffinProduct6",
  },
  {
    id: 21,
    productName: "Dress21",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/puffin/puffinProduct7",
  },
  {
    id: 22,
    productName: "Dress22",
    price: 999.0,
    productImage: product1,
    description: "It is a dress",
    productPage: "/puffin/puffinProduct8",
  },
];
